/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    sites: Site;
    bookings: Booking;
    'blocked-dates': BlockedDate;
    'event-inquiries': EventInquiry;
    addons: Addon;
    reviews: Review;
    pages: Page;
    requests: Request;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    sites: SitesSelect<false> | SitesSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    'blocked-dates': BlockedDatesSelect<false> | BlockedDatesSelect<true>;
    'event-inquiries': EventInquiriesSelect<false> | EventInquiriesSelect<true>;
    addons: AddonsSelect<false> | AddonsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    requests: RequestsSelect<false> | RequestsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
    'brand-guide': BrandGuide;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    'brand-guide': BrandGuideSelect<false> | BrandGuideSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Bookable campsites, van spots, and glamping units shown on the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites".
 */
export interface Site {
  id: number;
  name: string;
  /**
   * Used in the site URL — don't change after launch.
   */
  slug: string;
  type: 'tent' | 'van_solar' | 'van_power' | 'glamping';
  /**
   * Hidden sites disappear from the website immediately.
   */
  status: 'active' | 'inactive';
  /**
   * One-liner shown on browse cards.
   */
  shortDescription?: string | null;
  description?: string | null;
  /**
   * First photo is the cover image.
   */
  photos?:
    | {
        url: string;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  amenities?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  maxGuests: number;
  /**
   * Sun–Thu nightly rate (USD)
   */
  basePrice: number;
  /**
   * Fri & Sat nightly rate (USD)
   */
  weekendPrice: number;
  /**
   * This listing bundles other sites (e.g. Fairy Ring + Candy Cap).
   */
  isCombo?: boolean | null;
  /**
   * Slugs of the sites this combo includes. Booking the combo blocks them, and vice versa.
   */
  componentSiteSlugs?:
    | {
        slug: string;
        id?: string | null;
      }[]
    | null;
  latitude?: number | null;
  longitude?: number | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  /**
   * Paste this into Hipcamp → Calendar → Sync calendars → Import, and into Airbnb for the cottage. Bookings made here then block those dates there.
   */
  icalExportUrl?: string | null;
  /**
   * Their bookings block dates here. Hipcamp: Calendar → Sync calendars → Export → copy the link. Google Calendar: Settings → the calendar → "Secret address in iCal format". Syncs when you save, then every 15 minutes.
   */
  icalImportUrls?:
    | {
        platform?: ('hipcamp' | 'airbnb' | 'other') | null;
        /**
         * Ends in .ics — webcal:// links are fine too.
         */
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Last successful import.
   */
  icalLastSynced?: string | null;
  /**
   * What happened on the last import. Empty until the first sync.
   */
  icalLastError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Guest reservations. Never delete a booking — change its status instead.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  confirmationCode?: string | null;
  status: 'pending' | 'confirmed' | 'cancelled' | 'completed' | 'refunded';
  site?: (number | null) | Site;
  siteSlug: string;
  siteName: string;
  /**
   * To move a booking, cancel and rebook — this does not re-check availability.
   */
  checkIn: string;
  checkOut: string;
  nights?: number | null;
  guests?: number | null;
  guest: {
    firstName: string;
    lastName: string;
    email: string;
    phone?: string | null;
    specialRequests?: string | null;
  };
  addOns?:
    | {
        addOnId?: string | null;
        name?: string | null;
        quantity?: number | null;
        unitPrice?: number | null;
        perNight?: boolean | null;
        id?: string | null;
      }[]
    | null;
  nightlyBreakdown?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  subtotal?: number | null;
  addOnsTotal?: number | null;
  total?: number | null;
  waiverSigned?: boolean | null;
  waiverSignature?: string | null;
  source?: ('direct' | 'hipcamp' | 'airbnb') | null;
  magicLinkToken?: string | null;
  stripeSessionId?: string | null;
  stripePaymentIntent?: string | null;
  cancellationReason?: string | null;
  /**
   * When it was cancelled
   */
  cancelledAt?: string | null;
  /**
   * USD owed back per the cancellation policy.
   */
  refundAmount?: number | null;
  notifications?: {
    confirmationSentAt?: string | null;
    preArrivalSentAt?: string | null;
    dayBeforeSentAt?: string | null;
    postStaySentAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Date ranges a site can't be booked — maintenance, closures, or bookings from Hipcamp/Airbnb. End date works like a checkout date (not blocked itself).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blocked-dates".
 */
export interface BlockedDate {
  id: number;
  site?: (number | null) | Site;
  siteSlug: string;
  /**
   * YYYY-MM-DD, first blocked night
   */
  startDate: string;
  /**
   * YYYY-MM-DD, like a checkout date
   */
  endDate: string;
  reason: 'owner_block' | 'maintenance' | 'seasonal_closure' | 'ota_booking';
  source?: ('manual' | 'hipcamp' | 'airbnb' | 'other') | null;
  /**
   * Event ID from the synced calendar (managed automatically).
   */
  externalUid?: string | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Requests for The Loft & grounds — review and approve or decline.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-inquiries".
 */
export interface EventInquiry {
  id: number;
  status: 'pending' | 'approved' | 'declined' | 'converted';
  guestName: string;
  guestEmail: string;
  guestPhone?: string | null;
  eventType?: string | null;
  partySize?: number | null;
  preferredDates?: string | null;
  message?: string | null;
  /**
   * Internal — guests never see this.
   */
  adminNotes?: string | null;
  /**
   * USD
   */
  quotedPrice?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Optional extras guests can add during booking (firewood, rentals, etc.).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addons".
 */
export interface Addon {
  id: number;
  name: string;
  description?: string | null;
  /**
   * USD
   */
  price: number;
  /**
   * Charge per night instead of once per stay.
   */
  perNight?: boolean | null;
  maxQuantity: number;
  applicableSiteTypes: ('tent' | 'van_solar' | 'van_power' | 'glamping')[];
  active?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Guest reviews shown on site pages. Unpublish to hide one.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  author: string;
  /**
   * YYYY-MM-DD
   */
  date: string;
  rating: number;
  text: string;
  /**
   * Which site the stay was at.
   */
  siteSlug?: string | null;
  recommends?: boolean | null;
  published?: boolean | null;
  source?: ('hipcamp' | 'direct') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The marketing pages. Saving makes a draft; publishing puts it live.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * The homepage is "home". Others become /p/<slug>.
   */
  slug: string;
  /**
   * The complete page. Edited through the connector; every change is validated against the Brand Guide.
   */
  html: string;
  /**
   * What changed and why, on the last edit.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * New features and bigger changes, captured as they come up.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "requests".
 */
export interface Request {
  id: number;
  title: string;
  /**
   * What they want, in their words, and why.
   */
  detail?: string | null;
  status?: ('new' | 'planned' | 'building' | 'done' | 'declined') | null;
  /**
   * Small: an hour or two. Big: needs a plan and a test pass.
   */
  size?: ('unknown' | 'small' | 'big') | null;
  /**
   * Who asked.
   */
  requestedBy?: string | null;
  /**
   * What was decided or shipped.
   */
  response?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Uploaded photos. (Site photos currently use hosted URLs — uploads move to R2 at launch.)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * People who can log in to this admin panel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'owner';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'sites';
        value: number | Site;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'blocked-dates';
        value: number | BlockedDate;
      } | null)
    | ({
        relationTo: 'event-inquiries';
        value: number | EventInquiry;
      } | null)
    | ({
        relationTo: 'addons';
        value: number | Addon;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'requests';
        value: number | Request;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites_select".
 */
export interface SitesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  status?: T;
  shortDescription?: T;
  description?: T;
  photos?:
    | T
    | {
        url?: T;
        alt?: T;
        id?: T;
      };
  amenities?:
    | T
    | {
        label?: T;
        id?: T;
      };
  maxGuests?: T;
  basePrice?: T;
  weekendPrice?: T;
  isCombo?: T;
  componentSiteSlugs?:
    | T
    | {
        slug?: T;
        id?: T;
      };
  latitude?: T;
  longitude?: T;
  sortOrder?: T;
  icalExportUrl?: T;
  icalImportUrls?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  icalLastSynced?: T;
  icalLastError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  confirmationCode?: T;
  status?: T;
  site?: T;
  siteSlug?: T;
  siteName?: T;
  checkIn?: T;
  checkOut?: T;
  nights?: T;
  guests?: T;
  guest?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        email?: T;
        phone?: T;
        specialRequests?: T;
      };
  addOns?:
    | T
    | {
        addOnId?: T;
        name?: T;
        quantity?: T;
        unitPrice?: T;
        perNight?: T;
        id?: T;
      };
  nightlyBreakdown?: T;
  subtotal?: T;
  addOnsTotal?: T;
  total?: T;
  waiverSigned?: T;
  waiverSignature?: T;
  source?: T;
  magicLinkToken?: T;
  stripeSessionId?: T;
  stripePaymentIntent?: T;
  cancellationReason?: T;
  cancelledAt?: T;
  refundAmount?: T;
  notifications?:
    | T
    | {
        confirmationSentAt?: T;
        preArrivalSentAt?: T;
        dayBeforeSentAt?: T;
        postStaySentAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blocked-dates_select".
 */
export interface BlockedDatesSelect<T extends boolean = true> {
  site?: T;
  siteSlug?: T;
  startDate?: T;
  endDate?: T;
  reason?: T;
  source?: T;
  externalUid?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-inquiries_select".
 */
export interface EventInquiriesSelect<T extends boolean = true> {
  status?: T;
  guestName?: T;
  guestEmail?: T;
  guestPhone?: T;
  eventType?: T;
  partySize?: T;
  preferredDates?: T;
  message?: T;
  adminNotes?: T;
  quotedPrice?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addons_select".
 */
export interface AddonsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  price?: T;
  perNight?: T;
  maxQuantity?: T;
  applicableSiteTypes?: T;
  active?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  author?: T;
  date?: T;
  rating?: T;
  text?: T;
  siteSlug?: T;
  recommends?: T;
  published?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  html?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "requests_select".
 */
export interface RequestsSelect<T extends boolean = true> {
  title?: T;
  detail?: T;
  status?: T;
  size?: T;
  requestedBy?: T;
  response?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Property-wide info shown across the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  propertyName: string;
  location?: string | null;
  coordinates?: {
    lat?: number | null;
    lng?: number | null;
  };
  checkInTime?: string | null;
  checkOutTime?: string | null;
  quietHours?: string | null;
  cancellationPolicy?: string | null;
  /**
   * Drives the refund calculation when a guest cancels. Keep the policy text above in sync with these numbers.
   */
  cancellationTerms?: {
    /**
     * Cancel at least this many days before check-in → 100% refund.
     */
    fullRefundDays?: number | null;
    /**
     * Cancel at least this many days before check-in → partial refund.
     */
    partialRefundDays?: number | null;
    /**
     * Percent refunded in the partial window.
     */
    partialRefundPercent?: number | null;
  };
  houseRules?:
    | {
        rule: string;
        id?: string | null;
      }[]
    | null;
  sharedAmenities?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  host?: {
    names?: string | null;
    bio?: string | null;
    responseRate?: number | null;
    responseTime?: string | null;
    email?: string | null;
  };
  /**
   * Rating displayed on the website. Demo values — replace with real Hipcamp numbers before launch.
   */
  rating?: {
    average?: number | null;
    count?: number | null;
    /**
     * {"5": 380, "4": 35, ...}
     */
    breakdown?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * What the site may say and how it may say it. The LAW block at the bottom is enforced on every edit made through the connector.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-guide".
 */
export interface BrandGuide {
  id: number;
  /**
   * Must keep a parseable ```json LAW block, or all writes are refused.
   */
  markdown: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  propertyName?: T;
  location?: T;
  coordinates?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  checkInTime?: T;
  checkOutTime?: T;
  quietHours?: T;
  cancellationPolicy?: T;
  cancellationTerms?:
    | T
    | {
        fullRefundDays?: T;
        partialRefundDays?: T;
        partialRefundPercent?: T;
      };
  houseRules?:
    | T
    | {
        rule?: T;
        id?: T;
      };
  sharedAmenities?:
    | T
    | {
        label?: T;
        id?: T;
      };
  host?:
    | T
    | {
        names?: T;
        bio?: T;
        responseRate?: T;
        responseTime?: T;
        email?: T;
      };
  rating?:
    | T
    | {
        average?: T;
        count?: T;
        breakdown?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-guide_select".
 */
export interface BrandGuideSelect<T extends boolean = true> {
  markdown?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}